// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package bridge

import (
	"database/sql"
	"time"
)

type PaymentRequest struct {
	ID                    int64
	IdempotencyKey        string
	MerchantReference     sql.NullString
	AmountCents           int64
	Currency              string
	Status                string
	FailureCode           sql.NullString
	FailureMessage        sql.NullString
	CreatedAt             time.Time
	UpdatedAt             time.Time
	StripePaymentIntentID sql.NullString
}
