// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package bridge

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PaymentRequest struct {
	ID                    int64
	IdempotencyKey        string
	MerchantReference     pgtype.Text
	AmountCents           int64
	Currency              string
	PaymentMethod         string
	Installments          pgtype.Int4
	Status                string
	FailureCode           pgtype.Text
	FailureMessage        pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	StripePaymentIntentID pgtype.Text
}
