// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package bridge

import (
	"context"
	"database/sql"
	"time"
)

const createPaymentRequest = `-- name: CreatePaymentRequest :one
INSERT INTO payment_requests (
    idempotency_key,
    merchant_reference,
    amount_cents,
    currency,
    status,
    failure_code,
    failure_message,
    stripe_payment_intent_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, status, created_at, updated_at
`

type CreatePaymentRequestParams struct {
	IdempotencyKey        string
	MerchantReference     sql.NullString
	AmountCents           int64
	Currency              string
	Status                string
	FailureCode           sql.NullString
	FailureMessage        sql.NullString
	StripePaymentIntentID sql.NullString
}

type CreatePaymentRequestRow struct {
	ID        int64
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreatePaymentRequest(ctx context.Context, arg CreatePaymentRequestParams) (CreatePaymentRequestRow, error) {
	row := q.db.QueryRowContext(ctx, createPaymentRequest,
		arg.IdempotencyKey,
		arg.MerchantReference,
		arg.AmountCents,
		arg.Currency,
		arg.Status,
		arg.FailureCode,
		arg.FailureMessage,
		arg.StripePaymentIntentID,
	)
	var i CreatePaymentRequestRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
