// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package bridge

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentRequest = `-- name: CreatePaymentRequest :one
INSERT INTO payment_requests (
    idempotency_key,
    merchant_reference,
    amount_cents,
    currency,
    payment_method,
    status,
    failure_code,
    failure_message,
    stripe_payment_intent_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, payment_method, status, created_at, updated_at
`

type CreatePaymentRequestParams struct {
	IdempotencyKey        string
	MerchantReference     pgtype.Text
	AmountCents           int64
	Currency              string
	PaymentMethod         string
	Status                string
	FailureCode           pgtype.Text
	FailureMessage        pgtype.Text
	StripePaymentIntentID pgtype.Text
}

type CreatePaymentRequestRow struct {
	ID            int64
	PaymentMethod string
	Status        string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) CreatePaymentRequest(ctx context.Context, arg CreatePaymentRequestParams) (CreatePaymentRequestRow, error) {
	row := q.db.QueryRow(ctx, createPaymentRequest,
		arg.IdempotencyKey,
		arg.MerchantReference,
		arg.AmountCents,
		arg.Currency,
		arg.PaymentMethod,
		arg.Status,
		arg.FailureCode,
		arg.FailureMessage,
		arg.StripePaymentIntentID,
	)
	var i CreatePaymentRequestRow
	err := row.Scan(
		&i.ID,
		&i.PaymentMethod,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentRequestByIdempotencyKey = `-- name: GetPaymentRequestByIdempotencyKey :one
SELECT id, payment_method, status, created_at, updated_at
FROM payment_requests
WHERE idempotency_key = $1
`

type GetPaymentRequestByIdempotencyKeyRow struct {
	ID            int64
	PaymentMethod string
	Status        string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) GetPaymentRequestByIdempotencyKey(ctx context.Context, idempotencyKey string) (GetPaymentRequestByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getPaymentRequestByIdempotencyKey, idempotencyKey)
	var i GetPaymentRequestByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.PaymentMethod,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
