CREATE TABLE IF NOT EXISTS payments (
    id SERIAL PRIMARY KEY,
    amount_cents  BIGINT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);