// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package bridge

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PaymentAttempt struct {
	ID                    int32
	PaymentRequestID      string
	StripePaymentIntentID pgtype.Text
	AttemptNumber         int32
	Currency              string
	Status                string
	ErrorCode             pgtype.Text
	ErrorMessage          pgtype.Text
	Response              []byte
	CreatedAt             pgtype.Timestamptz
	ProcessedAt           pgtype.Timestamptz
}
