// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package bridge

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PaymentAttempt struct {
	ID                    int32
	PaymentRequestUuid    pgtype.UUID
	StripePaymentIntentID pgtype.Text
	StripeClientSecret    pgtype.Text
	AttemptNumber         int32
	Currency              string
	Status                string
	ErrorCode             pgtype.Text
	ErrorMessage          pgtype.Text
	Response              []byte
	CreatedAt             pgtype.Timestamptz
	ProcessedAt           pgtype.Timestamptz
}

type PaymentRequest struct {
	Uuid                  pgtype.UUID
	IdempotencyKey        string
	MerchantReference     pgtype.Text
	AmountCents           int64
	Currency              string
	PaymentMethod         string
	Installments          pgtype.Int4
	Status                string
	FailureCode           pgtype.Text
	FailureMessage        pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	StripePaymentIntentID pgtype.Text
}
