// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package bridge

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updatePaymentAttempt = `-- name: UpdatePaymentAttempt :exec
UPDATE payment_attempts
SET stripe_payment_intent_id = $2,
    attempt_number = $3,
    currency = $4,
    status = $5,
    error_code = $6,
    error_message = $7,
    response = $8,
    processed_at = NOW()
WHERE payment_request_id = $1
`

type UpdatePaymentAttemptParams struct {
	PaymentRequestID      string
	StripePaymentIntentID pgtype.Text
	AttemptNumber         int32
	Currency              string
	Status                string
	ErrorCode             pgtype.Text
	ErrorMessage          pgtype.Text
	Response              []byte
}

func (q *Queries) UpdatePaymentAttempt(ctx context.Context, arg UpdatePaymentAttemptParams) error {
	_, err := q.db.Exec(ctx, updatePaymentAttempt,
		arg.PaymentRequestID,
		arg.StripePaymentIntentID,
		arg.AttemptNumber,
		arg.Currency,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.Response,
	)
	return err
}
